name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        python manage.py test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      env:
        HOST: ${{ secrets.HOST }}
        USER: ${{ secrets.USER }}
        SSH_KEY: ${{ secrets.SSH_KEY }}
      run: |
        echo "$SSH_KEY" > id_rsa
        chmod 600 id_rsa  
      
        ssh -i id_rsa -o StrictHostKeyChecking=no $USER@$HOST << 'EOF'
          cd ~/new/EC2
          git pull origin main
          source ../venv/bin/activate
          pip install --upgrade pip 
          pip install -r requirements.txt
          python3 manage.py migrate
          python3 manage.py collectstatic --noinput
          
          # Kill any existing runserver process if it's running
          if pgrep -f "runserver" > /dev/null; then
              pkill -f runserver
          fi
          
          gunicorn Project.wsgi:application --bind 0.0.0.0:8000
  
        EOF
